In [5]:
import pandas as pd

# Path to your CSV file
file_path = '/kaggle/input/cluster/API_19_DS2_en_csv_v2_6300757.csv'

# Read the CSV file, skipping the first 4 lines which are metadata

def read_csv_custom(filepath, delimiter=',', header='infer', skiprows=None):
    """
    Custom function to read a CSV file into a pandas DataFrame with additional options.

    Parameters:
    - filepath (str): The path to the CSV file to be read. This is a mandatory parameter.
    - delimiter (str, optional): Character used to separate values in the file. Defaults to ','.
    - header (int, list of int, 'infer', optional): Row number(s) to use as column names. 
      Defaults to 'infer', which means that the first line of the file is used as column names. 
      If set to None, no header will be used.
    - skiprows (list-like, int or callable, optional): Line numbers to skip (0-indexed) or number 
      of lines to skip at the start of the file. Defaults to None.

    Returns:
    - pandas.DataFrame: DataFrame containing the data from the CSV file.

    Examples:
    >>> df1 = read_csv_custom('data.csv')
    >>> df2 = read_csv_custom('data.csv', delimiter=';', header=0)
    >>> df3 = read_csv_custom('data.csv', skiprows=2)

    Notes:
    - This function is a simple wrapper around pandas.read_csv() for more customized usage.
    - For more complex file reading scenarios, refer to pandas.read_csv documentation.
    """
    return pd.read_csv(filepath, delimiter=delimiter, header=header, skiprows=skiprows)
df = read_csv_custom(file_path, skiprows=4)
# Display the first few rows of the DataFrame
print(df.head())

   Aruba  ABW                                  Population, total  \
0  Aruba  ABW                       Population growth (annual %)
1  Aruba  ABW  Poverty headcount ratio at $2.15 a day (2017 P...
2  Aruba  ABW  Prevalence of underweight, weight for age (% o...
3  Aruba  ABW        Community health workers (per 1,000 people)
4  Aruba  ABW    Mortality rate, under-5 (per 1,000 live births)

      SP.POP.TOTL  54608     55811     56682     57475     58178     58782  \
0     SP.POP.GROW    NaN  2.179059  1.548572  1.389337  1.215721  1.032841
1     SI.POV.DDAY    NaN       NaN       NaN       NaN       NaN       NaN
2  SH.STA.MALN.ZS    NaN       NaN       NaN       NaN       NaN       NaN
3  SH.MED.CMHW.P3    NaN       NaN       NaN       NaN       NaN       NaN
4     SH.DYN.MORT    NaN       NaN       NaN       NaN       NaN       NaN

   ...    102880    103594    104257    104874    105439    105962   106442  \
0  ...  0.749301  0.691615  0.637959  0.590062  0.537296  0.494795  0.45197
1  ...       NaN       NaN       NaN       NaN       NaN       NaN      NaN
2  ...       NaN       NaN       NaN       NaN       NaN       NaN      NaN
3  ...       NaN       NaN       NaN       NaN       NaN       NaN      NaN
4  ...       NaN       NaN       NaN       NaN       NaN       NaN      NaN

     106585    106537    106445
0  0.134255 -0.045045 -0.086392
1       NaN       NaN       NaN
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN

[5 rows x 67 columns]

In [6]:
import csv

def read_csv_custom(filepath, delimiter=',', skip_header=False):
    """
    Custom function to read a CSV file into a list of dictionaries without using Pandas.

    Parameters:
    - filepath (str): The path to the CSV file to be read.
    - delimiter (str, optional): Character used to separate values in the file. Defaults to ','.
    - skip_header (bool, optional): Whether to skip the first row (header) of the CSV file. 
      Defaults to False.

    Returns:
    - list of dict: A list where each element is a dictionary representing a row in the CSV file. 
      Column headers are used as keys.

    Example:
    >>> data = read_csv_custom('data.csv')
    >>> data = read_csv_custom('data.csv', delimiter=';', skip_header=True)

    Note:
    - This function does not handle complex CSV features like multi-line fields.
    """
    data = []
    with open(filepath, 'r', newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter=delimiter)
        if skip_header:
            next(reader, None)  # Skip the header row
        for row in reader:
            data.append(row)
    return data

# Example usage of the function
data = read_csv_custom(file_path)
# df = pd.DataFrame(data)
# print(df.head())

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20212 entries, 0 to 20211
Data columns (total 67 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Aruba              20212 non-null  object
 1   ABW                20212 non-null  object
 2   Population, total  20212 non-null  object
 3   SP.POP.TOTL        20212 non-null  object
 4   54608              2490 non-null   float64
 5   55811              4069 non-null   float64
 6   56682              4103 non-null   float64
 7   57475              4120 non-null   float64
 8   58178              4161 non-null   float64
 9   58782              4190 non-null   float64
 10  59291              4196 non-null   float64
 11  59522              4201 non-null   float64
 12  59471              4212 non-null   float64
 13  59330              4217 non-null   float64
 14  59106              4757 non-null   float64
 15  58816              6097 non-null   float64
 16  58855              6116 non-null   float64
 17  59365              6119 non-null   float64
 18  60028              6123 non-null   float64
 19  60715              6175 non-null   float64
 20  61193              6199 non-null   float64
 21  61465              6216 non-null   float64
 22  61738              6213 non-null   float64
 23  62006              6222 non-null   float64
 24  62267              6277 non-null   float64
 25  62614              6343 non-null   float64
 26  63116              6338 non-null   float64
 27  63683              6356 non-null   float64
 28  64174              6370 non-null   float64
 29  64478              6403 non-null   float64
 30  64553              6418 non-null   float64
 31  64450              6488 non-null   float64
 32  64332              6481 non-null   float64
 33  64596              6487 non-null   float64
 34  65712              12581 non-null  float64
 35  67864              11047 non-null  float64
 36  70192              11431 non-null  float64
 37  72360              11495 non-null  float64
 38  74710              11580 non-null  float64
 39  77050              11645 non-null  float64
 40  79417              11652 non-null  float64
 41  81858              11619 non-null  float64
 42  84355              11668 non-null  float64
 43  86867              11787 non-null  float64
 44  89101              14531 non-null  float64
 45  90691              11990 non-null  float64
 46  91781              12051 non-null  float64
 47  92701              12059 non-null  float64
 48  93540              12214 non-null  float64
 49  94483              12771 non-null  float64
 50  95606              12373 non-null  float64
 51  96787              12403 non-null  float64
 52  97996              12710 non-null  float64
 53  99212              12482 non-null  float64
 54  100341             12731 non-null  float64
 55  101288             12380 non-null  float64
 56  102112             12343 non-null  float64
 57  102880             11377 non-null  float64
 58  103594             11447 non-null  float64
 59  104257             12814 non-null  float64
 60  104874             9860 non-null   float64
 61  105439             8155 non-null   float64
 62  105962             8180 non-null   float64
 63  106442             8346 non-null   float64
 64  106585             8091 non-null   float64
 65  106537             5212 non-null   float64
 66  106445             2761 non-null   float64
dtypes: float64(63), object(4)
memory usage: 10.3+ MB

In [9]:
data= df.dropna()
print("The total number of data-points after removing the rows with missing values are:", len(data))

The total number of data-points after removing the rows with missing values are: 995

In [10]:
data.describe()

,54608,55811,56682,57475,58178,58782,59291,59522,59471,59330,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
count,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,...,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02,9.950000e+02
mean,4.048732e+07,4.119609e+07,4.208894e+07,4.315065e+07,4.422843e+07,4.526467e+07,4.633961e+07,4.742182e+07,4.853412e+07,4.968346e+07,...,1.173905e+08,1.193230e+08,1.212586e+08,1.231990e+08,1.251470e+08,1.270754e+08,1.289744e+08,1.308257e+08,1.325390e+08,1.341298e+08
std,2.043335e+08,2.071240e+08,2.110722e+08,2.160772e+08,2.211236e+08,2.261385e+08,2.313996e+08,2.366525e+08,2.420646e+08,2.476891e+08,...,5.434200e+08,5.512978e+08,5.591347e+08,5.669567e+08,5.748079e+08,5.825068e+08,5.900235e+08,5.972625e+08,6.039024e+08,6.098609e+08
min,2.921227e-01,3.150861e-01,3.397334e-01,3.661880e-01,3.947513e-01,4.254729e-01,4.586037e-01,5.152986e-01,5.819781e-01,6.571884e-01,...,3.437522e-02,3.454085e-02,3.261351e-02,3.158219e-02,3.077838e-02,3.013746e-02,3.219431e-02,3.289014e-02,3.147370e-02,2.810989e-02
25%,2.432069e+01,2.551793e+01,2.533068e+01,2.563816e+01,2.583755e+01,2.620884e+01,2.646000e+01,2.680300e+01,2.716720e+01,2.757101e+01,...,3.851158e+01,3.918462e+01,3.975837e+01,4.013324e+01,4.051654e+01,4.084400e+01,4.145770e+01,4.163499e+01,4.204863e+01,4.250646e+01
50%,9.446000e+03,1.005000e+04,1.053200e+04,1.100400e+04,1.146500e+04,1.195200e+04,1.245200e+04,1.296700e+04,1.359700e+04,1.460000e+04,...,3.680600e+04,3.768500e+04,3.850300e+04,3.839800e+04,3.984400e+04,4.089500e+04,4.123900e+04,4.144500e+04,4.205000e+04,4.156900e+04
75%,2.762589e+06,2.819761e+06,2.891214e+06,2.981509e+06,3.060961e+06,3.130878e+06,3.189342e+06,3.257154e+06,3.356073e+06,3.402207e+06,...,8.112978e+06,8.362674e+06,8.546595e+06,8.731039e+06,8.962744e+06,9.134150e+06,9.274330e+06,9.349608e+06,9.540646e+06,9.600274e+06
max,3.031474e+09,3.072422e+09,3.126850e+09,3.193429e+09,3.260442e+09,3.328209e+09,3.398480e+09,3.468371e+09,3.540164e+09,3.614573e+09,...,7.229303e+09,7.317040e+09,7.403850e+09,7.490415e+09,7.576442e+09,7.660371e+09,7.741775e+09,7.820206e+09,7.888306e+09,7.950947e+09

In [17]:
data

,Aruba,ABW,"Population, total",SP.POP.TOTL,54608,55811,56682,57475,58178,58782,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
72,Africa Eastern and Southern,AFE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,1.456381e+01,1.481141e+01,1.506925e+01,1.534798e+01,1.564019e+01,1.594128e+01,...,3.347621e+01,3.393696e+01,3.442558e+01,3.489475e+01,3.535890e+01,3.584760e+01,3.633626e+01,3.682830e+01,3.732370e+01,3.782516e+01
73,Africa Eastern and Southern,AFE,Urban population,SP.URB.TOTL,1.903382e+07,1.987235e+07,2.077079e+07,2.173742e+07,2.277306e+07,2.387085e+07,...,1.901088e+08,1.980735e+08,2.065564e+08,2.150834e+08,2.237322e+08,2.329223e+08,2.424511e+08,2.523155e+08,2.623771e+08,2.726661e+08
75,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.306926e+08,1.341692e+08,1.378356e+08,1.416305e+08,1.456060e+08,1.497424e+08,...,5.678921e+08,5.836511e+08,6.000084e+08,6.163776e+08,6.327466e+08,6.497571e+08,6.672430e+08,6.851130e+08,7.029771e+08,7.208591e+08
91,Africa Eastern and Southern,AFE,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,6.444405e+00,6.564937e+00,6.690929e+00,6.815871e+00,6.947877e+00,7.085666e+00,...,1.365722e+01,1.381416e+01,1.393429e+01,1.406590e+01,1.420788e+01,1.433700e+01,1.445516e+01,1.458105e+01,1.472133e+01,1.487672e+01
148,Afghanistan,AFG,Urban population (% of total population),SP.URB.TOTL.IN.ZS,8.401000e+00,8.684000e+00,8.976000e+00,9.276000e+00,9.586000e+00,9.904000e+00,...,2.437300e+01,2.458700e+01,2.480300e+01,2.502000e+01,2.525000e+01,2.549500e+01,2.575400e+01,2.602600e+01,2.631400e+01,2.661600e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20079,Zambia,ZMB,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,2.915340e+00,3.143517e+00,3.389273e+00,3.661470e+00,3.998799e+00,4.365472e+00,...,1.304941e+01,1.324996e+01,1.346104e+01,1.368156e+01,1.391039e+01,1.415037e+01,1.439908e+01,1.465646e+01,1.492310e+01,1.519552e+01
20136,Zimbabwe,ZWE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,1.260800e+01,1.282100e+01,1.308200e+01,1.357800e+01,1.409200e+01,1.462000e+01,...,3.265400e+01,3.250400e+01,3.238500e+01,3.229600e+01,3.223700e+01,3.220900e+01,3.221000e+01,3.224200e+01,3.230300e+01,3.239500e+01
20137,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4.799000e+05,5.033460e+05,5.297920e+05,5.672790e+05,6.074120e+05,6.501730e+05,...,4.426387e+06,4.503674e+06,4.584076e+06,4.667645e+06,4.755312e+06,4.848158e+06,4.945719e+06,5.052214e+06,5.166388e+06,5.287038e+06
20139,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.806310e+06,3.925952e+06,4.049778e+06,4.177931e+06,4.310332e+06,4.447149e+06,...,1.355542e+07,1.385575e+07,1.415494e+07,1.445270e+07,1.475110e+07,1.505218e+07,1.535461e+07,1.566967e+07,1.599352e+07,1.632054e+07
20155,Zimbabwe,ZWE,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,6.514919e+00,6.640555e+00,6.768371e+00,6.897936e+00,7.030178e+00,7.163601e+00,...,1.098906e+01,1.078729e+01,1.059505e+01,1.041191e+01,1.023585e+01,1.006509e+01,9.907847e+00,9.763578e+00,9.640302e+00,9.544661e+00

In [18]:
import csv
import pandas as pd

def transpose_csv(df):
    """
    Reads a CSV file into a DataFrame, transposes it, and returns the transposed DataFrame.

    Parameters:
    - dataframe

    Returns:
    - pandas.DataFrame: Transposed DataFrame.

    Example:
    >>> transposed_df = transpose_csv(df)
    """


    transposed_df = df.T  # or df.transpose()

    return transposed_df

# Example usage
transposed_df = transpose_csv(data)

In [20]:
transposed_df

,72,73,75,91,148,149,151,167,224,225,...,20003,20060,20061,20063,20071,20079,20136,20137,20139,20155
Aruba,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Africa Western and Central,Africa Western and Central,...,South Africa,Zambia,Zambia,Zambia,Zambia,Zambia,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe
ABW,AFE,AFE,AFE,AFE,AFG,AFG,AFG,AFG,AFW,AFW,...,ZAF,ZMB,ZMB,ZMB,ZMB,ZMB,ZWE,ZWE,ZWE,ZWE
"Population, total",Urban population (% of total population),Urban population,"Population, total",Population in urban agglomerations of more tha...,Urban population (% of total population),Urban population,"Population, total",Population in urban agglomerations of more tha...,Urban population (% of total population),Urban population,...,Population in urban agglomerations of more tha...,Urban population (% of total population),Urban population,"Population, total","Agriculture, forestry, and fishing, value adde...",Population in urban agglomerations of more tha...,Urban population (% of total population),Urban population,"Population, total",Population in urban agglomerations of more tha...
SP.POP.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.TOTL,SP.POP.TOTL,EN.URB.MCTY.TL.ZS,SP.URB.TOTL.IN.ZS,SP.URB.TOTL,SP.POP.TOTL,EN.URB.MCTY.TL.ZS,SP.URB.TOTL.IN.ZS,SP.URB.TOTL,...,EN.URB.MCTY.TL.ZS,SP.URB.TOTL.IN.ZS,SP.URB.TOTL,SP.POP.TOTL,NV.AGR.TOTL.ZS,EN.URB.MCTY.TL.ZS,SP.URB.TOTL.IN.ZS,SP.URB.TOTL,SP.POP.TOTL,EN.URB.MCTY.TL.ZS
54608,14.56381,19033821.0,130692579.0,6.444405,8.401,724373.0,8622466.0,3.309401,14.705391,14301917.0,...,24.323394,18.145,566021.0,3119430.0,11.460629,2.91534,12.608,479900.0,3806310.0,6.514919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105962,35.847598,232922327.0,649757148.0,14.337003,25.495,9353296.0,36686784.0,10.935191,46.649426,206492202.0,...,35.578753,43.521,7762359.0,17835893.0,3.341124,14.150365,32.209,4848158.0,15052184.0,10.065091
106442,36.336259,242451140.0,667242986.0,14.455163,25.754,9727157.0,37769499.0,10.892466,47.255413,214684207.0,...,35.870818,44.072,8100644.0,18380477.0,2.860775,14.399077,32.21,4945719.0,15354608.0,9.907847
106585,36.828302,252315481.0,685112979.0,14.581055,26.026,10142913.0,38972230.0,10.832154,47.857831,223107995.0,...,36.176168,44.629,8447250.0,18927715.0,2.977086,14.65646,32.242,5052214.0,15669666.0,9.763578
106537,37.323699,262377061.0,702977106.0,14.721332,26.314,10551772.0,40099462.0,10.812539,48.454806,231704052.0,...,36.544603,45.192,8800295.0,19473125.0,3.000918,14.923095,32.303,5166388.0,15993524.0,9.640302
106445,37.825158,272666107.0,720859132.0,14.876724,26.616,10946834.0,41128771.0,10.838841,49.047385,240494466.0,...,36.949707,45.761,9160288.0,20017675.0,3.094016,15.195516,32.395,5287038.0,16320537.0,9.544661

In [ ]:
import pandas as pd

def read_clean_and_transpose_df(data):
    """
    Converts a list of dictionaries or a list of lists to a DataFrame, 
    performs basic cleaning tasks, and transposes it.

    The cleaning tasks include dropping rows with missing (NA) values.

    Parameters:
    - data (list of dict or list of lists): The data to be converted to a DataFrame, cleaned, and transposed.

    Returns:
    - pandas.DataFrame: Cleaned and transposed DataFrame.

    Example:
    >>> data = [['A', 'B', 'C'], [1, 2, 3], [4, 5, None]]
    >>> cleaned_transposed_df = read_clean_and_transpose_df(data)
    """

    # Convert data to DataFrame
    if isinstance(data[0], dict):
        # If data is a list of dictionaries
        df = pd.DataFrame(data)
    else:
        # If data is a list of lists
        df = pd.DataFrame(data[1:], columns=data[0])

    # Drop rows with missing values
    df_cleaned = df.dropna()
    

    # Transpose the DataFrame
    transposed_df = df_cleaned.T

    return transposed_df

# Example usage
# Assuming 'data' is your list
cleaned_transposed_df = read_clean_and_transpose_df(df)

In [19]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

# Assuming X is your data
X=transposed_df
# Normalize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Using the Elbow Method to find the optimal number of clusters
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

# Plotting the results
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

# Choose the number of clusters (k) and fit the model
k = 3  # Example number, replace with the chosen k
kmeans = KMeans(n_clusters=k, init='k-means++', random_state=42)
y_kmeans = kmeans.fit_predict(X_scaled)

# Calculating silhouette score
silhouette_avg = silhouette_score(X_scaled, y_kmeans)
print(f"The average silhouette score for {k} clusters is: {silhouette_avg}")

# Additional analysis and interpretation...

ValueError: could not convert string to float: 'Africa Eastern and Southern'